version: '3.8'

services:
  door-calculator-api:
    build: .
    ports:
      - "${HOST_PORT:-8001}:${CONTAINER_PORT:-8000}"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${CONTAINER_PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${CONTAINER_PORT:-8000}/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s